### ISSUE TITLE
Layout of social media icons in footer incorrect (overlap?)

### ISSUE THREAD

**Issue by stephan-koenig** [ubc-cpsc/jekyll-clf-theme#1]
Hi,

The social media icons in the footer appear to have two different versions overlapping.

![Screen Shot 2022-09-20 at 1 40 59 PM Large](https://user-images.githubusercontent.com/11433347/191382033-e5acc065-7df8-4204-aa21-6afdcff265c3.jpeg)

I believe this is caused by updating CLF to 7.0.5 (reverting to 7.0.4 seems to fix the issue).

https://github.com/ubc-cpsc/jekyll-clf-theme/blob/fb8a33d3e0a11117b4b0b26001cee48bfa322816/_includes/head.html#L56

**Comment by joelpittet** [comment]
Oh yeah, that looks off, I'll take care of that soon
