### ISSUE TITLE
Missing dependency: Jekyll Scholar

### ISSUE THREAD

**Issue by natashamm** [ubc-cpsc/jekyll-clf-theme#11]
Error when running `bundle exec jekyll serve`

`Dependency Error: Yikes! It looks like you don't have jekyll-scholar or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. If you've run Jekyll with `bundle exec`, ensure that you have included the jekyll-scholar gem in your Gemfile as well. The full error message from Ruby is: 'cannot load such file -- jekyll-scholar' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!`

Interestingly enough I don't get this error when I just use this as a theme (i.e. in https://github.com/ubc-cpsc/jekyll-course-template/) - note it is not using any jekyll scholar functionalities

**Comment by joelpittet** [comment]
Don't think I forgot this, I just got back from being away. 

Dependencies are tricky in ruby... maybe the the theme doesn't get the other gems?
I am guessing `bundle install` doesn't resolve the dependency issue?
