### ISSUE TITLE
Ordered list formatting

### ISSUE THREAD

**Issue by stephan-koenig** [ubc-cpsc/jekyll-clf-theme#4]
Hi,

Ordered lists have brackets surrounding the number markers instead of numbers followed by a period used in UBC CLF.

![ordered_list](https://user-images.githubusercontent.com/11433347/217913266-c9b0b892-8a2a-4d83-bd94-2a51fe8940d4.png)

**Comment by joelpittet** [comment]
@stephan-koenig Can you point me to the Markdown that generates this?

**Comment by stephan-koenig** [comment]
Thanks, @joelpittet! Here is the file: [PrairieLearnUBC.github.io/invigilation.md at initial-website-content · PrairieLearnUBC/PrairieLearnUBC.github.io](https://github.com/PrairieLearnUBC/PrairieLearnUBC.github.io/blob/initial-website-content/invigilation.md)

**Comment by joelpittet** [comment]
Thanks I think I've fixed this, there was some unneeded styles around typography that I just ripped out. @stephan-koenig
