### ISSUE TITLE
Update with the latest UBC CS Social Media Links

### ISSUE THREAD

**Issue by natashamm** [ubc-cpsc/jekyll-clf-theme#7]
Current social media links with the jekyll theme:

<img width="143" alt="Screenshot 2024-03-27 at 4 17 44 PM" src="https://github.com/ubc-cpsc/jekyll-clf-theme/assets/22650546/423b3e1c-4dc7-41f8-b5fe-4b244117bdf0">

Current social media links on cs.ubc.ca

<img width="333" alt="Screenshot 2024-03-27 at 4 17 38 PM" src="https://github.com/ubc-cpsc/jekyll-clf-theme/assets/22650546/3934925a-a556-417e-9462-4b57eb0a87d7">

**Comment by joelpittet** [comment]
Just about to add LinkedIn too BTW, and we are debating changing the Twitter logo to the X...
